
openapi: 3.0.0
info:
  title: PDF Server API
  description: Vollständige API zur PDF-Erzeugung mit Template-Engines
  version: "1.0.0"
servers:
  - url: http://localhost:3000
    description: Lokale Entwicklungsumgebung

paths:
  /api/templates:
    get:
      summary: Liste aller verfügbaren Templates
      responses:
        '200':
          description: JSON-Array mit Template-Namen
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /api/template/{templateName}:
    get:
      summary: Ruft ein bestimmtes Template ab
      parameters:
        - name: templateName
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Inhalt des Templates
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: Template nicht gefunden

    post:
      summary: Überschreibt ein bestehendes Template
      parameters:
        - name: templateName
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
      responses:
        '200':
          description: Template erfolgreich gespeichert
        '400':
          description: Fehlerhafte Eingabe

  /api/generate/{templateName}:
    post:
      summary: Generiert ein PDF auf Basis eines Template-Namens
      parameters:
        - name: templateName
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  description: JSON-Daten für das Template
      responses:
        '200':
          description: Erfolgreich generiertes PDF
          content:
            application/pdf:
              schema:
                type: string
                format: binary
        '400':
          description: Fehlerhafte Anfrage

  /api/generate/donc:
    post:
      summary: Spezialisierter Endpunkt für DONC-PDFs
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                assetId:
                  type: string
                returnOrderId:
                  type: string
                contactId:
                  type: string
      responses:
        '200':
          description: DONC-PDF erfolgreich erstellt
          content:
            application/pdf:
              schema:
                type: string
                format: binary
        '400':
          description: Fehlerhafte Anfrage

  /api/templates/upload:
    post:
      summary: Upload eines neuen Templates (ZIP oder HTML+JSON)
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                template:
                  type: string
                  format: binary
                data:
                  type: string
                  format: binary
      responses:
        '200':
          description: Template erfolgreich hochgeladen
        '400':
          description: Fehlerhafter Upload

components: {}
