name: Deploy to AWS App Runner

on:
  push:
    branches: [main]  # angepasst für deinen Branch

jobs:
  deploy:
    name: Node.js App Runner Build (Code Repo Mode)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Build and test (optional)
        run: echo "No build step needed for Express/Puppeteer"

      - name: Info only – AWS App Runner will deploy this repo
        run: |
          echo "App Runner will auto-deploy this branch via Source Code mode."
          echo "Ensure package.json and Procfile are correct for Node.js runtime."
